// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_TJyO1-gYUttAWtqfrsddSsCoMJLuYQ',
    appId: '1:1064571125693:web:69b85270f38614cb805cd4',
    messagingSenderId: '1064571125693',
    projectId: 'fifth-sunup-291909',
    authDomain: 'fifth-sunup-291909.firebaseapp.com',
    storageBucket: 'fifth-sunup-291909.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCWwQIg0RMwjHvnrSc1r686Kja5_rKb0c',
    appId: '1:1064571125693:android:795626b0c4b0fbd0805cd4',
    messagingSenderId: '1064571125693',
    projectId: 'fifth-sunup-291909',
    storageBucket: 'fifth-sunup-291909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSZg4fs47tttP6r_hA7eYGtI7AHNTTcA',
    appId: '1:1064571125693:ios:df072e7ad278cc59805cd4',
    messagingSenderId: '1064571125693',
    projectId: 'fifth-sunup-291909',
    storageBucket: 'fifth-sunup-291909.appspot.com',
    iosClientId: '1064571125693-2skb8ghi458dmno899jilbd8jko0juh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZSZg4fs47tttP6r_hA7eYGtI7AHNTTcA',
    appId: '1:1064571125693:ios:fec9cdf9b7389e7f805cd4',
    messagingSenderId: '1064571125693',
    projectId: 'fifth-sunup-291909',
    storageBucket: 'fifth-sunup-291909.appspot.com',
    iosClientId: '1064571125693-878124d19t987sjcjgrpop0isg6u58f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
